SOURCES := $(shell find . -name '*.dfy')
LOG_DIR = ./Logs
SPLIT_LOG_DIR = ./SplitLogs

clean-split:
	@rm -rf $(SPLIT_LOG_DIR)
	@rm -rf Makefile

clean-log:
	@rm -rf $(LOG_DIR)

clean-mk:
	@rm -rf Makefile

dafny:
	@for i in $(SOURCES); do \
   		d=$$(date +%s); \
		timeout 200s dafny /trace /compile:0 /print:$(LOG_DIR)/$$i.print /dprint:$(LOG_DIR)/$$i.dprint /proverLog:$(LOG_DIR)/$$i.proverlog $$i /printTooltips > $(LOG_DIR)/$$i.trace; \
		echo "$$i,	$$(($$(date +%s)-d))"; \
	done

dafny-simpl:
	@for i in $(SOURCES); do \
		echo "======[$$i]======"; \
		dafny /trace /compile:0 > $(LOG_DIR)/$$i.trace-simpl; \
	done

dafny-split:
	@for i in $(SOURCES); do \
   		d=$$(date +%s); \
		timeout 200s dafny /trace /compile:0 /print:$(SPLIT_LOG_DIR)/$$i.print /dprint:$(SPLIT_LOG_DIR)/$$i.dprint /proverLog:$(SPLIT_LOG_DIR)/$$i.proverlog $$i /printTooltips /proverOpt:O:smt.CASE_SPLIT=1 > $(SPLIT_LOG_DIR)/$$i.trace; \
		echo "$$i,	$$(($$(date +%s)-d))"; \
	done

.PHONY: clean-split clean-log clean-mk dafny dafny-simpl dafny-split
